-- AlterTable
ALTER TABLE "Experiencia" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Formacaos" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Habilidades" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
